### ISSUE TITLE
import brickfront error

### ISSUE THREAD

**Issue by jgalan** [4Kaylum/Brickfront#2]
Hi,

I am on linux trying to install and use brickfront. I downloaded and build/install it.

Using 

`python setup.py build
`
and

`sudo python setup.py install
`
But when I try to run python importing brickfront, it complains with the following error.

python test.py (just contains one line with "import brickfront")

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import brickfront
  File "/home/javier/git/Brickfront/brickfront/__init__.py", line 1, in <module>
    from .client import Client
  File "/home/javier/git/Brickfront/brickfront/client.py", line 22
    def __init__(self, apiKey: str):
```

Sorry if this is not the right place to post this.
J

**Comment by 4Kaylum** [comment]
Is that your full traceback? It seems to completely miss out the part that includes the error.

**Comment by jgalan** [comment]
Yes, almost all I get. I only forgot last line

```
javier@javier-ThinkPad-X230:~/git/Brickfront$ python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import brickfront
  File "/home/javier/git/Brickfront/brickfront/__init__.py", line 1, in <module>
    from .client import Client
  File "/home/javier/git/Brickfront/brickfront/client.py", line 22
    def __init__(self, apiKey: str):
                             ^
SyntaxError: invalid syntax
javier@javier-ThinkPad-X230:~/git/Brickfront$ 
```

**Comment by 4Kaylum** [comment]
The `invalid syntax` part is exactly the part I would have needed. I imagine that's the `:str` part. What version of Python are you using?

**Comment by jgalan** [comment]
Python 2.7.6

**Comment by jgalan** [comment]
Ubuntu 14

**Comment by 4Kaylum** [comment]
Type hints were introduced in a later version of Python. Give me 10 minutes and I'll push an update that'll remove those for you. It *is* meant to be compatible with your version of Python.

**Comment by 4Kaylum** [comment]
Removed type hinting with https://github.com/4Kaylum/Brickfront/commit/8393bce98a4d531d4af19e660dc842689f0345e5

**Comment by jgalan** [comment]
Yes! That solved the problem
Thanks!

**Comment by jgalan** [comment]
However, there are some issues when I try to stablish a connection. I think it is a matter of updating to a newer version of python at the end...
```

javier@javier-ThinkPad-X230:~/git/Brickfront$ python test.py 
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

....
....
```

**Comment by jgalan** [comment]
Which python version are you using?

**Comment by 4Kaylum** [comment]
Try installing `requests[security]` instead of `requests`. I am using the newest stable version of Python, Python3.6. You may have issues upgrading from Py2 to Py3.
